### ISSUE TITLE
Disable custom products

### ISSUE THREAD

**Issue by RobertAndreasFritsch** [NiHoel/Anno1800Calculator#10]
Feature:
Add a toggle button to the products, that toggles the calculation for this product.
For example this may be helpful if you want to produce schnapps but no beer.
ATM you can only toggle all luxury goods.

**Comment by NiHoel** [comment]
This is the next feature I plan to implement.
I plan to do it the following way: Each final product under the sections farmers, workers, etc. gets a checkbox to "ban" it for this tier. 

Then, you can even ban products by tier, i.e. no sewing machines for obreros.

It will nee some implementation effort to still display the card although the product is not produced for this tier.
