### ISSUE TITLE
Feature Request\Contribution - Input for All Resources

### ISSUE THREAD

**Issue by amitdey1987** [NiHoel/Anno1800Calculator#20]
Input for all resources (not just construction material) (e.g. for Hops Island where we can specify no. of hops to be produced that is consumed outside of the island)
If you are open to contributions, I would like to work on this.

**Comment by NiHoel** [comment]
You can activate the option "Show input field for additional production". That should satisfy your needs.
Moreover, the calculator is designed to represent the global production (and not per island). See https://anno1800.fandom.com/wiki/Anno_1800_Needs_Calculators_Overview for others (you might be interested in http://deathwingstudios.com/Anno1800Calculator/index.html).
