### ISSUE TITLE
Siederrei bei 200 Arbeitern ?

### ISSUE THREAD

**Issue by MarkusSB** [NiHoel/Anno1800Calculator#22]
Bei der Eingabe von 600 Bauern und 100 Arbeitern, wird mit angezeigt, dass ich eine Siederei bauen muss, dieser ist im Spiel aber erst ab 300 Arbeitern freigeschaltet.

**Comment by NiHoel** [comment]
Der Rechner berücksichtigt die Freischaltbedingungen nicht, da diese im weiteren Spielverlauf (für den der Rechner gedacht ist) nicht mehr relevant sind. Außerdem kann man sich in der jetzigen Version ausrechnen lassen, wie viel Produktion man für eine gewisse Anzahl an Einwohnern (z. B. 200 Arbeiter) mehr braucht (z. B. an Sidereien).

Einen Überblick über Warenrechner zu Anno 1800 kann man hier finden: [https://anno1800.fandom.com/wiki/Anno_1800_Needs_Calculators_Overview](https://anno1800.fandom.com/wiki/Anno_1800_Needs_Calculators_Overview)
