### ISSUE TITLE
Required Workforce should be calculated from existing number of buildings

### ISSUE THREAD

**Issue by britiscurious** [NiHoel/Anno1800Calculator#24]
Why is the required number of buildings editable?

IMHO it should be fix based on inhabitants and other buildings in the production chains.
The required workforce should be calculated from existing number of buildings instead.

I am using the Calculator for single islands and use the existing number of buildings for planned over-production to export some goods to other islands.

Unfortunatley the required workforce ignores if existing number of buildings is higher than required number of buildings what leads to wrong required workforce calculation.

**Comment by NiHoel** [comment]
The intended way of including planned over-production is to enable the option "Show input field for additional production". Then, at the bottom of each tile one can enter the amount of over-production (or under-production if one enters a negative number) in tons per minute.
