### ISSUE TITLE
Wish: multi island support

### ISSUE THREAD

**Issue by britiscurious** [NiHoel/Anno1800Calculator#25]
It would be a great extension if the calculator would allow to enter an island name and consequently could be used for multiple islands in parallel.
To keep an overview of import/export I prefer a per-island-calculation.

**Comment by NiHoel** [comment]
Managing multiple islands seperatly is not the goal of this calculator. Moreover, the autosave feature works incorrect when working with multiple tabs. So, I see no sense to encourage this by implementing a naming feature.

One can find an overview for other calculators here: https://anno1800.fandom.com/wiki/Anno_1800_Needs_Calculators_Overview
Consider: http://deathwingstudios.com/Anno1800Calculator/index.html

**Comment by britiscurious** [comment]
@NiHoel 

With few modifications I am using Anno1800Calculator for multiple islands.
Therefore, I have created a copy of index.html for each island (e.g. Ditchwater) and performed the following modification (diff):

```
7c7,8
<     <title>Anno 1800 Calculator</title>
---
> 	<meta name="island_id" content="ditchwater">
> 	<title>Ditchwater</title>
```

For proper storage of values and settings I have also modified the AnnoCalculator.js:

```
562a563,573
>     let dotIslandId = '';
>     let islandIdDot = '';
>     const metas = document.getElementsByTagName('meta');
> 
>     for (let i = 0; i < metas.length; i++) {
>         if (metas[i].getAttribute('name') === 'island_id') {
>             dotIslandId = '.' + metas[i].getAttribute('content');
>             islandIdDot = metas[i].getAttribute('content') + '.';
>         }
>     }
> 
571c582
<             let id = "settings." + attr;
---
>             let id = "settings." + islandIdDot + attr;
599c610
<                 let id = f.guid + ".percentBoost";
---
>                 let id = f.guid + dotIslandId + ".percentBoost";
615c626
<                 let id = f.guid + ".existingBuildings";
---
>                 let id = f.guid + dotIslandId + ".existingBuildings";
636c647
<                     let id = p.guid + ".percentBoost";
---
>                     let id = p.guid + dotIslandId + ".percentBoost";
646c657
<                     let id = p.guid + ".fixedFactory";
---
>                     let id = p.guid + dotIslandId + ".fixedFactory";
665c676
<             let id = i.guid + ".checked";
---
>             let id = i.guid + dotIslandId + ".checked";
679c690
<             let id = l.guid + ".amount";
---
>             let id = l.guid + dotIslandId + ".amount";
704c715
<                     let id = `${l.guid}[${n.guid}].checked`;
---
>                     let id = `${l.guid}[${n.guid}]${dotIslandId}.checked`;
713c724
<                     let id = `${l.guid}[${n.guid}].percentBoost`;
---
>                     id = `${l.guid}[${n.guid}]${dotIslandId}.percentBoost`;
757c768
<                     let id = b.guid + ".existingBuildings"
---
>                     let id = b.guid + dotIslandId + ".existingBuildings"
775c786
<             let id = f.guid + ".extraAmount";
---
>             let id = f.guid + dotIslandId + ".extraAmount";

```

**Comment by NiHoel** [comment]
Multi island support seems to be the most requested feature. Unfortunately, it takes the most effort to implement:
- User friendly implementation to add/delete islands (tabs on the site?)
- Make all computation island based (should be possible by putting the global variables into a class)
- Update bindings
- Ability to add extra amount for goods that are not (indirectly) needed on this island (e.g. population only goes up to workers but lime should be produced)
- The server must correctly read the name of the island that population count can be updated per island.
- How to handle production chains spanning 3 or more islands? I think updating the import / export amount for every affected island whenever the demand increases is too annoying.

**Comment by NiHoel** [comment]
The ability to name the tab and import / export configuration should satisfy the requirements behind multi island support.

**Comment by britiscurious** [comment]
@NiHoel Did you try a multi island scenario yourself? With your solution you can only use one island at a time. Exporting/importing data to work with the next island-> way to uncomfortable.
With my proposal I am able to have calculators for all my islands open in parrallel. Therefor the island id as part of the storage ids was a crucial part.

**Comment by NiHoel** [comment]
The current workflow is to open multiple tabs and load the configurations for all the islands. When you finished playing, you have to save all of them manually. But of course, local storage and the Anno Server won't work then. 
For your solution one needs proper instructions + a good migration strategy from the current non-island based calculator to the multi-island scenario. 
I mean you can fork this calculator and just use your own version or you can make a pull request addressing these issues.

**Comment by britiscurious** [comment]
Hi, I created a fork:
https://github.com/britiscurious/Anno1800Calculator
But I'm not a developer. :-) Rather I try to figure out how something works and how I can alter it to make it fit to my needs. :-)

**Comment by NiHoel** [comment]
@britiscurious Complete rework of multi island support. This should satisfy your needs. You can even import your old one-island-saves and it automatically creates a new island.

**Comment by britiscurious** [comment]
@NiHoel 
Thumbs up! What a surprise. Did not play Anno for a while now and wanted to check your updates.
Now I found the Multi Island Support. Thanks a lot!
