### ISSUE TITLE
wrong calculation of Pig Farm need when input field for additional production is used for Slaughterhouse

### ISSUE THREAD

**Issue by britiscurious** [NiHoel/Anno1800Calculator#27]
reset the calculator
enable "Highlight missing buildings"
enable "Show input field for additional production (negative values possible)"
enter 1000 Workers
enter -5 in Slaughterhouse additional production field (value will be set to -1,000002)

Observed behavior:
Pig Farm is still highlighted as missing building

Expectation:
Pig Farm is no longer required and disappears

(check the same with Schnapps Distillery/Potato or Framework Knitters/Sheep Farm -> here it works properly)

**Comment by britiscurious** [comment]
Sorry, I missed the Soap Factory. So behavior is OK.

**Comment by NiHoel** [comment]
Why did you re-open it?

**Comment by britiscurious** [comment]
Sorry, missed to save the corresponding comment.
There are some cases where the calculation is inaccurate, probably due to rounding errors, e.g.:

reset the calculator
enable "Highlight missing buildings"
enable "Show input field for additional production (negative values possible)"
enter 20 Farmers
enter 980 Workers
enter -5 in Slaughterhouse additional production field (value will be set to -0,9800019600000001)
enter -5 in Soap Factory additional production field (value will be set to -0,40833366)

Observed behavior:
Pig Farm is still highlighted as missing building
with 0,01 required buildings and 5.551115123125783e-17 additional production

**Comment by NiHoel** [comment]
@britiscurious You can test the fixes on the branch [population_reader](https://github.com/NiHoel/Anno1800Calculator/tree/population_reader). Just ignore the update notification.
