### ISSUE TITLE
Lacking dark theme

### ISSUE THREAD

**Issue by fogil** [NiHoel/Anno1800Calculator#30]
Please add dark theme, it's 2019, please.

All you need to do is add:

body.backgroundColor: #333;
text.color: #dedede;

**Comment by NiHoel** [comment]
If you have tried it, you see it is not that easy. A lot more css properties need to be changed. Maybe you want to try changing it and create a pull request.

![Anno1800Calculator-dark-naive](https://user-images.githubusercontent.com/28017252/63413684-7e512c00-c3fa-11e9-979d-e94269c31f0d.PNG)
