### ISSUE TITLE
Problems with Logger and Clay (no image yet, started a new game) being detected as New World in the Old World

### ISSUE THREAD

**Issue by auddie2015** [NiHoel/Anno1800Calculator#36]
Are being detected as being New World sources.

![Annotation 2019-12-22 210122](https://user-images.githubusercontent.com/15572587/71331315-98f9f580-24ff-11ea-9785-3bb06635fb89.png)

**Comment by NiHoel** [comment]
Working on a (sophisticated) solution, see
https://github.com/Dejauxvue/AnnoCalculatorServer/issues/11#issuecomment-566794328

**Comment by auddie2015** [comment]
Thank you! This program is already awesome. 

Now that you point out the thread, I can see this is what it is about. I speak no German at all! :-D

**Comment by NiHoel** [comment]
Solved with release 2.2 of the server.
