### ISSUE TITLE
Required Workforce is not working after bright harvest update

### ISSUE THREAD

**Issue by WESTKINz** [NiHoel/Anno1800Calculator#38]
Required workforce is always displaying zero even after you input the residents value.
![image](https://user-images.githubusercontent.com/16592792/83810541-33b24f00-a6b0-11ea-9de2-e2b157cfdec1.png)

I have tried clearing cookie and I have also tried running this website on different computers but still same issue.

**Comment by Nodagoscha** [comment]
Workforce still not calculated correctly.
1. Insert 10000 investors
2. Change productivity on "glasses" to 200%
3. Nothing changes on neeeded Workforce
4. Press reset
5. Needed Workforce show some number....

Tested in Chorme and Brave
