### ISSUE TITLE
Calculator showing incorrect Grain usage

### ISSUE THREAD

**Issue by ItsTrinda** [NiHoel/Anno1800Calculator#41]
I have 2 grain farms, 1 flour mill, 1 bakery, and 1 pig farm with an attached Silo. (I also have 3 sheep farms with attached silos, but they aren't receiving grain for some reason)

The calculator reports I'm using 1.21x Grain, but the ingame statistics show that I'm using 2, with the potential to use 3 grain.

**Comment by NiHoel** [comment]
The required amount of grain for bakeries depends on the actual consumption by the inhabitants. So if they only consume 1.01 t of bread per minute, then this leads to an overall demand of 1.21 t of grain per minute (one silo included). The ingame statistics calculates the demand based on the number of buildings processing the good, so it comes up with 2.21 t/min.

**Comment by ItsTrinda** [comment]
I'm using the number of houses mode, does that not assume max usage for a house?

**Comment by NiHoel** [comment]
It does not matter whether a house contains 10/20 or 20/20 inhabitants. The consumption is always the same.
