### ISSUE TITLE
percental consumption modification not working / How to handle Town Hall Items

### ISSUE THREAD

**Issue by Friday13th87** [NiHoel/Anno1800Calculator#42]
Hey there,
Many thanks for the great work done here.
As there is now Town Hall Item implementation (is there?), what would be the desired way of handling the production/usage of my people?

The option in settings "Show input field for percental consumption modification" is doing nothing for me
The only way i can see so far is to put in the needed amount of buildings manually by calculating it, but then i wouldnt need a programm anymore.
It would be good to have the option to just input the needed value by hand.
Maybe there is a better workaround for that.

**Comment by NiHoel** [comment]
You have to scroll down to modify the percental consumption modification. It is listed under consumption per tier.

**Comment by Friday13th87** [comment]
ah, found that now, thanks for the very quick reply. input mask for the value would be helpful as well - or is there a way to get those percentages form a ingame statistig / table?

**Comment by Friday13th87** [comment]
much harder is that the percental consumption is per  citizen group and i can only find the total needed amount.
for example bred (for all islands):
Calculator tells me the needed amount is 23.46t/min - thats correct for the raw value with my citizens.
i have different town hall items in use on some islands and in my ingame statistic the overall need is 14t/min (rounded to the next higher number i assume)
as different citizen groups consuming that item pretty hard to get to that value or is there any trick i am missing?
even harder for items like beer or anything else used by more then 2 groups

**Comment by NiHoel** [comment]
You can ban the good for all tiers except for one for a short time, then you see the amount for that tier -> adjust the percental consumption to fit.
