### ISSUE TITLE
Falsche Kalkulation für Traktoren

### ISSUE THREAD

**Issue by Lasagne45** [NiHoel/Anno1800Calculator#43]
Durch den Hacken bei Traktoren wird die Produktivität auf 300% gesetzt. Was zu einen drittel des Bedarfs führt. Was aber nicht berücksichtigt wird ist, dass man auch 50% mehr Felder hat die bewirtschaftet werden. Meiner Kalkulation nach (für Kartoffeln und Baumwolle) steigt die Produktivität allerdings auf 400%.

![Unbenannt](https://user-images.githubusercontent.com/47713042/87852955-9ed57f00-c906-11ea-8107-f26ee663c76b.PNG)

Das ist die Produktion bei 10 Kartoffelhöfen mit Tranktoren. Maximal also 80 bzw 8 pro Farm.

![Unbenannt 2](https://user-images.githubusercontent.com/47713042/87852970-b7459980-c906-11ea-9b5e-fb2e9eb6e289.PNG)

Der Rechner gibt aber nur 6 pro Farm an was eben 1/3 zu wenig ist.

Grüße Max

Edit can repost in english if necessary

**Comment by NiHoel** [comment]
Die Traktoren bringen +200% Produktivität und 1 Zusatzware in jedem dritten Zyklus.
Du kannst Zusatzwaren unter Einstellungen -> "Zeige Eingabefeld für Zusatzproduktion" anzeigen und manuell eingeben.

**Comment by Lasagne45** [comment]
Ich kann auch 400% Produktion einstellen. Wäre ja aber trotzdem praktisch wenn es durch den Hacken direkt stimmt

**Comment by NiHoel** [comment]
Ich bin noch dabei, mir eine gute Lösung zu überlegen.
Die 400%-Variante funktioniert z.B. nicht mehr, wenn man weitere Items verwendet.
Einige Items haben auch Zusatzwaren, wenn ich jetzt bei Traktormodulen diese automatisch miteinrechne und bei den Items nicht, könnte dies ebenfalls zu Verwirrungen führen.

**Comment by Lasagne45** [comment]
Und was halt auch geht ist, dass man Traktoren verwendet ohne das man Treibstoff hat.

**Comment by NiHoel** [comment]
Wie soll das denn gehen? Ohne Treibstoffversorgung geht doch die Produktivität wieder zurück.

**Comment by Lasagne45** [comment]
Ja aber die Felderweiterung geht ja trotzdem. Was soweit ich weiß auch die Produktion steigert.

**Comment by NiHoel** [comment]
Nein, die Produktionssteigerung ist alleine an den Kraftstoffverbrauch gekoppelt.

**Comment by NiHoel** [comment]
Mit letztem Update gefixt.
