### ISSUE TITLE
Not all products for new dlc are showing under the product tabs 

### ISSUE THREAD

**Issue by Electroblade** [NiHoel/Anno1800Calculator#47]
The Lobsters and Candles do not show under the product tabs.

Also every time the calculator updates through the server the setting for Input number of houses instead of residents is ticked and I have to uncheck  it each time, the other settings I use remains the way I set it.

Thanks for the great calculator. Keep up the good work.

**Comment by NiHoel** [comment]
I fixed this in the latest release. Please update your local calculator.

**Comment by Electroblade** [comment]
Thank you
