### ISSUE TITLE
request: Global good requirement modifier

### ISSUE THREAD

**Issue by polski-g** [NiHoel/Anno1800Calculator#49]
Could you add a global option to change all requirements based on an arbitrary value? ie: With anarchist propaganda, there is a +25% good requirement modifier.

**Comment by NiHoel** [comment]
This will come with the next update of the calculator. You can test the beta version here:
https://drive.google.com/drive/folders/19EVjDvOuCHlKOEhWOWdeuhar2Jqfqlk_?usp=sharing


Usage: Download all files, extract and open index.html with the browser.

I'd be interested to know your thoughts about usability, understandability (what you can do and how to achieve that), and design.

**Comment by polski-g** [comment]
First impression is that having the settings menu be greater than one level deep is a bit confusing. I think it would be easier to navigate if "Show input field for additional production (negative values possible)" and "Show input field for percental consumption modification" were just buttons on the main screen or on the navbar at the top.

**Comment by NiHoel** [comment]
Keeping the balance between fast accessibility vs. a clean interface for newcomers is always a challenge. I admit that a two level settings menu is not the best way. On the other hand I'm about to integrate trade. This would mean three additional buttons on the main screen which would need to be well distinguishable. 

It is intended that people will use the factory config dialog more often where one can also equip items.
