### ISSUE TITLE
Mandatory Island Prefix

### ISSUE THREAD

**Issue by SunD76** [NiHoel/Anno1800Calculator#50]
Hi! Can we have the opportunity to not select a prefix when adding a new island or having an option to add additional citizen types to an selected island? I'd like to keep track of my export routes seperated as I currently fulfill needs between Enbesa <-> Cape Trelawney and Old World <-> Arctic.
So I'd highly appreciate when I can add the Arctic People to Old World and Enbesan Citizens to Cape Trelawney.
Thanks for consideration or any feedback highly appreciated!

**Comment by SunD76** [comment]
Sorry, took me some time to figure out how to set up the routes correctly which does exactly what I asked for. Sorry for bothering.

**Comment by NiHoel** [comment]
You can export the configuration, delete the session entry for the island and re-import it. Islands without sessions will display all tiers. Just in case you stumble over other use cases where this would be convenient.

**Comment by SunD76** [comment]
Thanks for the info!
Anyways is there a way that "all Islands" automatically displays all information entered from correct prefixed islands without having to enter all information once again?

**Comment by NiHoel** [comment]
Then it would no longer be possible no manually enter values for islands and have a purely global calculator. Moreover, it would be hard to create a comprehensive summary when islands have different items equipped, boost or effects applied.

**Comment by SunD76** [comment]
Yes, you have a point there! Thanks for the replies!!
