### ISSUE TITLE
Snapps and Rum Chains dont calculate

### ISSUE THREAD

**Issue by niwdEnamtrooP** [NiHoel/Anno1800Calculator#51]
The Snapps and rum chains don't calculate when the site is run localy

**Comment by NiHoel** [comment]
I cannot reproduce the issue.
Are you sure that you didn't lock them?

What happens if you reset everything? Export the configuration, open the console (F12), enter "localStorage.clear()" (without the quotes) and reloat.

**Comment by niwdEnamtrooP** [comment]
Yes the reset worked thank you!! 

And i love the calculator by the way beautiful.
