### ISSUE TITLE
Feature Request: Display data from running Anno on different computer

### ISSUE THREAD

**Issue by kickinJohn** [NiHoel/Anno1800Calculator#53]
Hi,

first of all, great programm, I love it ! :) 

I have Calculator 4.1 + Server 5.2 running on the same machine. Having only one monitor, you always have to tab out of the game to check the current status. I'd like to ask for a feature to seperate calculator and server machinewise. Server of course running the same computer as Anno does, calculator display on a laptop for example. I was not sure if this is a feature request of the calculator or the server..

That would be a killer feature :) 
Thanks !

**Comment by NiHoel** [comment]
That is actually pretty easy. In line 1969 of AnnoCalculator.js replace localhost by the ip address of your desktop PC.

https://github.com/NiHoel/Anno1800Calculator/blob/79155b673f89cab64849e7ae2ea2d3e417251e55/AnnoCalculator.js#L1969

But there are some things to keep in mind:
1. You desktop computer must be reachable from the device where you run the code (e.g. be in the same network, inter device communication must be enabled by the router)
2. The port 8000 must be open for incoming traffic (and responses). Check windows defender and / or your antivirus software


Then, you can receive updates on any mobile device. Even on Android or iPhone. The trick there is to open a local website: https://android.stackexchange.com/a/4777

**Comment by NiHoel** [comment]
Due to the caveats I do not offer a UI to enter the IP address. I fear that I'd then receive a lot of complaints "doesn't work for me".

**Comment by kickinJohn** [comment]
Thanks for the fast reply!
Yes I also played around with the AnnoCalculator.js. Even though inter communication in home network is enabled and firewalls are turned off, accessing http://<myip>:8000/AnnoServer/Population from a different machine than server gives HTTP 400 invalid hostname. Is the server expecting localhost? Unfortunately I haven't found any clue to this in the https://github.com/NiHoel/Anno1800UXEnhancer/ files.

But nevertheless, as this is Server related and not Client Calculator related anymore I would just close this issue :) Thanks again !

**Comment by NiHoel** [comment]
I uploaded a new server version here:
https://drive.google.com/drive/folders/1Vsy3kXGe11d28pISqR82VpaCGdZaNtyi?usp=sharing

The Readme contains instructions how to access the server from remote devices.

**Comment by kickinJohn** [comment]
Works like a charm with -h flag to start up the server! Thank you very much :)

**Comment by FIrgolitsch** [comment]
I'm not sure if I should comment here, but seeing that the version that is on drive differs from the one available at https://github.com/NiHoel/Anno1800UXEnhancer/ isn't the same I'll try my chances here.

Whenever I try to start the server with the -h flag I get the following message:
![image](https://user-images.githubusercontent.com/16656315/109798726-68d9d680-7c1b-11eb-9381-6f8d040ad0d9.png)

I'm running the cmd prompt as admin, as I was getting errors before when trying it with a non-admin shell. The verbose logging didn't give me any additional info.

**Comment by NiHoel** [comment]
I uploaded a new version with a command line flag. See the README.

I'm impressed that you manage to compile all the dependencies and the server!
