### ISSUE TITLE
Selecting François Strindberg for Jewelry does NOT remove the need for pearls

### ISSUE THREAD

**Issue by vanth0me** [NiHoel/Anno1800Calculator#56]
As said in the titel. François Strindberg completely removes the need for pearls. It seems the calculator does not know this. It has been around since Update 8.1 according to this [thread](https://www.reddit.com/r/anno/comments/g6xln2/anno1800_anyone_know_how_fran%C3%A7ois_strindberg/)

**Comment by NiHoel** [comment]
I'm aware of it since I added this item. But I didn't bother to implement this special effect. Jewels are the only production chain that use pearls and one can simply ignore the need.

**Comment by vanth0me** [comment]
That's fair. I checked and it is indeed only used for the Jewelers. Thank you for responding and closing the issue.
