### ISSUE TITLE
[Feature request] Calculate workforce bonus

### ISSUE THREAD

**Issue by vanth0me** [NiHoel/Anno1800Calculator#57]
Hello,

Is it possible to calculate the need for increase/decrease in workforce that comes from items. I have some production buildings that don't need any workforce at all, but it still calculates in the end. This would make it very hard to use the required workforce as an indication for how many people you actually need.

So this isn't technically an issue, but more a feature request.
Thanks for your hard work!

**Comment by NiHoel** [comment]
Feature under consideration for next release:

In factory configuration dialog: Input field for percentage workforce requirement (100% - full to 0% - none)

**Comment by NiHoel** [comment]
The next release will include the feature. You can test the preview version here and give feedback: https://nihoel.github.io/Anno1800Calculator-preview/

**Comment by vanth0me** [comment]
Thank you for your work! I will test it tomorrow or the weekend and let you know what I find.

**Comment by vanth0me** [comment]
Just tested it and it seems to work fine. UI seems good too. This will definitely help a lot, since some new world production chains can have a huge number of workers! I'll probably start a new playthrough using this calculator from the start :)

Thank you again for your hard work <3
