### ISSUE TITLE
Anno Calculator Error

### ISSUE THREAD

**Issue by Zitrusfan** [NiHoel/Anno1800Calculator#60]
Hi. :)
Beim Ausführen deines AnnoCalculators bekomme ich folgende Fehlermeldung. (siehe Bild) 
![Error](https://user-images.githubusercontent.com/81584328/112877862-8e95b680-90c7-11eb-8e91-d6efb58341cd.PNG)

Habe auch darauf geachtet, dass mein Java und meine Runtime-environment auf dem neusten Stand sind. Kannst du mir weiterhelfen? 

Lg!

**Comment by NiHoel** [comment]
Du musst die index.html mit dem Browser öffnen.
