### ISSUE TITLE
it seems the calculation for consumprion may be off slightly

### ISSUE THREAD

**Issue by darkstar48507** [NiHoel/Anno1800Calculator#65]
![screenshot_2021-06-06-14-44-19](https://user-images.githubusercontent.com/85458145/120938025-684b5300-c6d6-11eb-8fca-e323fa1305a3.jpg)
![anno 1800 issue](https://user-images.githubusercontent.com/85458145/120938115-e871b880-c6d6-11eb-8b7e-dce747ae4275.png)

i could just be doing something wrong but it seems that the consumption numbers are off, some slightly and some a lot

if this is just me how do i fix it?

attached are an in game screen shot for Schnapps and an image of the calculator for Schnapps

**Comment by darkstar48507** [comment]
also what happened to the old check box for power?

**Comment by NiHoel** [comment]
Hello darkstar48507,

the consumption is affected by the following:

- number of houses (open the population level configuration menu and check that it matches the ingame values)
- effects and festivals that reduce the effect (icons in the upper part of the house info panel)

I never had check boxes for power. Do you confuse it with another calculator?

**Comment by darkstar48507** [comment]
right, the population is updated correctly, there were no additional in game modifiers at the time of screen shot
i was using Schnapps as an example (it was right there) but its also off for fish, i have 5 fishers and am producing 1 extra but the calculator says i need 7

**Comment by darkstar48507** [comment]
unless with the last update/DLC they adjusted the consumption values and didnt tell anyone?

**Comment by NiHoel** [comment]
No, they didn't change the values. And if they had, I would have noticed that.

What about bar or newspaper?

**Comment by darkstar48507** [comment]
right, the newspaper, i. am. an. idiot.

sorry for the waste of time
