### ISSUE TITLE
Enbesa demands incorrect

### ISSUE THREAD

**Issue by alexknapp009** [NiHoel/Anno1800Calculator#67]
Hello,

i am using the anno tool which is I think awesome! Unfortunately the demands for inhabitors of Enbesa are incorrect, at least some of them. I think Goat milk and Finery are ok, but i am quite sure that there is something wrong with hibiscus tee, dried meat, Ceramics, Tapestries, Seafood Stew, Clay Pipes, and Illuminated Script. Maybe there where some changes in game update 11. I can say for sure that i have constant problems with supply of these goods ingame. Do you have any source with more accurate data? This would really help here. :) THANK YOU IN ADVANCE FOR THIS GREAT TOOL! BR, Alex

**Comment by NiHoel** [comment]
The consumption values are extracted from the game files.  They didn't change them in the last two updates (I checked it while writing the response).

There can be several reasons why the consumption in the statistics menu differs from the output of the calculator: newspaper, items, buffs, ...

I can help you troubleshooting, if you send me screenshots of
* the production tab from the statistics screen with the needs in question shown
* the population tab from the statistics screen
* the house window

**Comment by alexknapp009** [comment]
Thank you for your quick response. I do not use items or buffs in enbesa for primary goods, also the newspaper has actually no effect on the consumption. In all other worlds it works perfectly. I will send you screenshots as soon as i start the game the next time. Thank you very much in advance.
