### ISSUE TITLE
[Feature Request] Option to use the commuter pier

### ISSUE THREAD

**Issue by BastiNbg** [NiHoel/Anno1800Calculator#72]
It is possible to have goods transported from one island to another. This should also be possible for the necessary workforce so that they can be transferred to another island by commuter pier.

**Comment by NiHoel** [comment]
Since DLC11 might bring something similar to a commter pier, I'll postpose the feature until then.

**Comment by NiHoel** [comment]
The feature will be included in the update for DLC 11
