### ISSUE TITLE
Bright harvest flags are doing the wrong math

### ISSUE THREAD

**Issue by Ahadoron** [NiHoel/Anno1800Calculator#75]
I hope I didn't forget about something, but it seems the math behind the bright harvest flags is not correct.
If I have a need for 10 Potato fields without the harvest flag and then activate the flag it sais I need 2,5 fields.
Although it shows that the productivity is 300% now it calculates as if it were 400%.
The silo flag missbehaves equally but there its calculating like the productivity was 267% instead of 200%.

Since the ingame stats do tell me that in all cases i'm producing too less to fullfill the needs, I think that's an error in the calculator.

In any case, thank you for the great calculator and merry christmas :-)

**Comment by NiHoel** [comment]
This is correct since silos and tractors give 1 extra good every 3rd cycle.
