### ISSUE TITLE
Dockland bug

### ISSUE THREAD

**Issue by Anno123456** [NiHoel/Anno1800Calculator#80]
Hi,

When using docklands to import something on an islands there is a bug that wont let 
you use the same item twice for exporting.

Example i want to export work cloths to import grain which will work. 
When i want export work cloths again to import hop i cant select work cloths anymore from the list, it is gone. 
Every item i want to use the second time for the export is no longer on the list. 

When selecting 'all islands' it still works but when you select a specific island it doesnt anymore. 

Could you take a look at this?

Thanks

**Comment by NiHoel** [comment]
I implemented a bug fix that one cannot import and export the same good on normal islands. However, the fix introduced a new bug, as you noticed. I'll need some time to fix it. As a workaround, you can create both contracts from the Framework Knitters configuration dialog.
