### ISSUE TITLE
Reset button does not reset the count for some population tiers

### ISSUE THREAD

**Issue by dwo0** [NiHoel/Anno1800Calculator#82]
* **Steps to reproduce** — Enter a value of the desired population for each population tier. Press the Reset button.
* **Expected results** — The value for the desired population for each tier is reset to zero.
* **Actual results** — The values for Farmers, Engineers, Investors, Jornaleros and Obreros are reset as expected. The values for Workers, Artisans, Tourists, explorers, Technicians, Shepherds, Elders and Scholars do not change.

Before:

![before](https://user-images.githubusercontent.com/10255349/168453628-ac48e8fe-6a99-4a3d-bef2-83f14f7205c4.png)

After:

![after](https://user-images.githubusercontent.com/10255349/168453639-46387cab-64a4-4895-9af6-0b49017fddd9.png)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

**Comment by NiHoel** [comment]
Fixed: [https://nihoel.github.io/Anno1800Calculator-preview/](https://nihoel.github.io/Anno1800Calculator-preview/)
The next release of the calculator depends on the upcoming Game Updates of Anno.
