### ISSUE TITLE
Obreros don't show demand for hats and others...

### ISSUE THREAD

**Issue by Zarubine** [NiHoel/Anno1800Calculator#85]
Obreros demand seems incomplete. Hats, beer, sewing machines are not calculated. 
![Screenshot (13)](https://user-images.githubusercontent.com/109220393/178730831-340e1bf1-a960-469c-b78e-38030b861bc1.png)
![Screenshot (14)](https://user-images.githubusercontent.com/109220393/178730840-b6eee19b-63d3-4387-9c7e-44046d670543.png)

**Comment by Zarubine** [comment]
Thanks for the quick reply! Hats unlock at 600 Obreros and I have 1,680. My people certainly want them. I checked the max. residents button but that didn't change it either. 
![Screenshot (15)](https://user-images.githubusercontent.com/109220393/178736021-1f415f5c-18ec-491e-bb5f-f6e016bab51f.png)

As for your question, I tend to not change the default settings. I haven't yet reached a high enough population to really need all the bells and whistles.

**Comment by NiHoel** [comment]
This number determines the unlock:
![grafik](https://user-images.githubusercontent.com/28017252/178737156-3aa1464f-0e29-4ea3-b648-f77f6b617ab7.png)

Even when you unlock all in the calculator, you can still exclude them from the calculation by unticking the checkbox:
![grafik](https://user-images.githubusercontent.com/28017252/178737497-cef475ee-52ed-4c4d-a448-c3efeaa5fafa.png)

**Comment by Zarubine** [comment]
Thanks, that solved it. I thought when you click the max. resident button it automatically uses the max. number of people for the calculation.

**Comment by NiHoel** [comment]
No, the radio button determines which number you see in the main window. That should not affect the calculation at all.
