### ISSUE TITLE
Negative Consumption from Skyscrapers

### ISSUE THREAD

**Issue by JesterJ** [NiHoel/Anno1800Calculator#89]
If i change the per house number of investors from 605 to 300 and then write 200 in the building count then they will generate a negative consumption
![image](https://user-images.githubusercontent.com/6771216/198879141-fdc5f877-7f10-48e3-9808-36982991a2fb.png)

**Comment by JesterJ** [comment]
I investigated the issue a little further, and it seems to drop of as you set it to 430 max residents. Thats 175 lower than 605, which is the number that should be the baseline for max pop in investor skyscrapers level 5. After looking into the params.js, i could see that the influx of residents from lifestyle needs is increased by a factor equal to the skyscraper tier. If added together this results in the aforementioned max pop of 605 even though the "residentMax" value is 175.
I'm not sure if its intentional that the resident influx should increase with the tier of the building and after correcting the numbers in the params.js file the issue seems to be solved and it correctly calculates the required goods.

**Comment by NiHoel** [comment]
It's correct that you get more residents from lifestyle needs with higher skyscraper levels. You can verify this in the game.
The 605 is the minimum - you must not enter smaller values (I will fix that this is currently not enforced)

**Comment by NiHoel** [comment]
![correct-wrong-input](https://user-images.githubusercontent.com/28017252/199115089-e9042fad-a732-422b-8762-4ac29d3e9378.gif)

**Comment by JesterJ** [comment]
Ah okay, i haven't tried it that far yet with lifestyle needs, and it did not make sense when comparing it to the wiki, however the wiki does contain multiple errors in regards to lifestyle needs so im noty surprised.
Nice that you make it enforce it, that will make it clear that it is intentional.
Maybe you could also add a small explanation of it under the skyscraper description in the readme?
Thank you very much for the explanation, i depend on your calculator as it is the only complete one out there so thanks so much :)
