### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Schmerzkeks** [NiHoel/Anno1800Calculator#9]
Maybe you can put the Interface in a Tab and you can Name the Tab with your Townname or what ever you wanna.
So you can manage more towns in 1 Explorer Tab. Now i have to open a new Tab in my Firefox for a new Town. With this Tab system in your Calculator you only need 1 Explorer Tab and can manage all in there.

**Comment by NiHoel** [comment]
The scope of this calculator is for planning global production. Individual tabs would also make it neccessary to store values per tab. 

You may have a look here:
https://www.reddit.com/r/anno/comments/bkqv44/community_resource_megathread/

(especially: http://deathwingstudios.com/Anno1800Calculator/index.html)
