### ISSUE TITLE
Can't select some lifestyle needs

### ISSUE THREAD

**Issue by Lotan21** [NiHoel/Anno1800Calculator#92]
Only 6 out of the 9 lifestyle needs can be selected for each population tier.
For example soap for farmers is not available.

**Comment by NiHoel** [comment]
The calculator is not yet updated for GU 16 (that's why they are missing / incorrect).
Until then you can find a preview version with GU 16 here: [https://nihoel.github.io/Anno1800Calculator-preview/](https://nihoel.github.io/Anno1800Calculator-preview/)

**Comment by Lotan21** [comment]
ah, I did not play for a while and was not aware that this was feature of the new update, thanks for the info
