### ISSUE TITLE
Köhlerei

### ISSUE THREAD

**Issue by acgk90** [NiHoel/Anno1800Calculator#93]
Guten Tag, 

Ich habe ein Problem mit der Köhlerei. Wenn ich in den Regioneneinstellungen von der Köhlerei auf Kohlenmine umstelle, 
setzt der Calculator bei der Köhlerei automatisch die Produktion auf 0 t/min.  Das bewirkt dass der Spezialist mit Zusatzware Kautschuk auch nicht mehr mitgerechnet wird und diese Ware nun nicht mehr in Betracht gezogen wird bei der Hochradproduktion. Das betrifft alle ähnliche Produktionen mit Zusatzwaren. Vorher konnte man das mit dem Kästchen Zusatzwaren manuell dazugeben, Dies ist nun leider nicht mehr dar Fall. 
MfG

**Comment by NiHoel** [comment]
Entschuldige die späte Antwort:

Du kannst jetzt in den Einstellungen "Fabriken voll auslasten", dann erzwingst du eine Produktion, wenn du Fabriken hast.
Alternativ kannst du Kohle von der Köhlerei auf eine Fake-Insel exportieren.
