### ISSUE TITLE
Brasserie Patron Mertens

### ISSUE THREAD

**Issue by suxkar** [NiHoel/Anno1800Calculator#95]
Hello!
Am i missing something or Brasserie Patron Mertens is missing? I can't find him among the the need consumption items

**Comment by suxkar** [comment]
So this is quite weird.. If I run the calculator locally, Mertens is there, if I run it from github, it's not there.

I would also add another question: in the main page, after all the factories, I can't find the part where production is divided into population tiers anymore. Was it removed?

**Comment by NiHoel** [comment]
In Github it's there, too.
Please upload a screenshot.

Yes, I removed the production per population part at the end of the page. But you can find everything and more when you click on the market button in the population configuration dialog.

**Comment by suxkar** [comment]
My bad, I think i was looking for it in the Artisans tab. Artisans drink beer but they do not have need for pub, so Mertens doesn't apply to them, so it makes sense that it doesn't appear in their menu. It's actually the second time I make this mistake while designing a game. I'm very dumb sorry for wasting your time.

Thank you again for this amazing tool.

**Comment by suxkar** [comment]
Since I'm at it, one last question: I can't find the items that increase workforce in the options, are they not implemented? Any workaround other that doing the % calculation myself?

**Comment by NiHoel** [comment]
Yes, production and workforce boosts must be calculated manually as there are too many options: items, palace effects etc.
