### ISSUE TITLE
Bar Black muscovy wrong buff text

### ISSUE THREAD

**Issue by tefracky** [NiHoel/Anno1800Calculator#96]
Hello,

thanks again for your great calculator! Unfortunately, in the `Need Consumption`, Absinth is listed two times, while Black muscovy is completely missing. However, one of the Absinth has exactly the buffs of black muscovy, so it is just a naming problem. The same problem occurs for Coupe de Grace/Eclairs.

```
            "guid": 133361,
            "iconPath": "data/ui/2kimages/main/3dicons/recipes/icon_black_muscovy.png",
            "locaText": {
                "chinese": "苦艾酒",
                "english": "Absinthe",
                "french": "Absinthe",
                "german": "Absinth",
                "italian": "Assenzio",
                "japanese": "アブサン",
                "korean": "압생트",
                "polish": "Absynt",
                "russian": "Абсент",
                "spanish": "Absenta",
                "taiwanese": "苦艾酒"
            },
```

**Comment by NiHoel** [comment]
![grafik](https://user-images.githubusercontent.com/28017252/221427425-89c7ba4d-ec8c-4a04-9181-0bd8a035a367.png)

**Comment by tefracky** [comment]
![grafik](https://user-images.githubusercontent.com/4464088/221428238-c2020b75-7a09-40f7-bb03-3e4524be4519.png)

**Comment by NiHoel** [comment]
If the devs fix the text in-game, I can run my extraction prgram and it is fixed as well. Waiting for the next GU.
